[[pages]]
path = "/"
screenshotTimestamp = "2026-04-05T18:47:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b4c7cf1f-e4f4-4439-a41d-ad77c151e703/a6ddf275-0dbf-4a5d-b029-d1ce49cf718c/DWBEfXh"

[[pages]]
path = "/booking"
screenshotTimestamp = "2026-04-05T18:47:13Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b4c7cf1f-e4f4-4439-a41d-ad77c151e703/a6ddf275-0dbf-4a5d-b029-d1ce49cf718c/uF1Afp1"
